# Generated by Django 6.0.3 on 2026-06-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='managed_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deans', to='attendance.programme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('dept_head', 'Department Head'), ('dean', 'Dean'), ('admin', 'Admin'), ('student', 'Student')], default='teacher', max_length=10),
        ),
    ]
