# Generated by Django 6.0.3 on 2026-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_course_department_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_telegram_chat_id',
            field=models.CharField(blank=True, help_text='Automatically filled when parent starts the bot', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_telegram',
            field=models.CharField(help_text='Telegram username', max_length=100),
        ),
    ]
