# Generated by Django 5.2.15 on 2026-08-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_academicyear_id_alter_attendancerecord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='secondary_teachers',
            field=models.ManyToManyField(blank=True, related_name='secondary_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_offerings', to=settings.AUTH_USER_MODEL),
        ),
    ]
